export enum RequiredParameterName {
  ACCESS_TOKENS = 'ACCESS_TOKENS',
  ROLES = 'ROLES',
  CLIENT_SETTINGS = 'CLIENT_SETTINGS',
  API_ACCESS_ROLES = 'API_ACCESS_ROLES',
  OPERATORS = 'OPERATORS',
  STUDIES = 'STUDIES',
  FORMS = 'FORMS',
  REPORT_TEMPLATES = 'REPORT_TEMPLATES',
  INSTRUMENTS = 'INSTRUMENTS',
  COLLECTORS = 'COLLECTORS',
  SAMPLE_TYPES = 'SAMPLE_TYPES',
  LOCATIONS = 'LOCATIONS',
  EMAIL_GROUPS = 'EMAIL_GROUPS',
  UPLOADED = 'UPLOADED'
}
